apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-azure-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
