---          
kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: postgres
  type: ClusterIP
